version: "3"
services:
  backend:
    build:
      context: ./blog-backend  # Path to the backend folder
    ports:
      - "5000:5000"  # Expose backend to localhost:5000
    environment:
      - MONGODB_URI=mongodb+srv://azizprains06:rootroot@cluster0.5vugn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0  # Use MongoDB URI (replace with actual)
    volumes:
      - ./blog-backend:/app  # Sync local backend code to the container
      - /app/node_modules  # Prevent overwriting node_modules inside container
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend

  frontend:
    build:
      context: ./blog-frontend  # Path to the frontend folder
    ports:
      - "80:80"  # Expose frontend to localhost:80
    volumes:
      - ./blog-frontend:/app  # Sync local frontend code to the container
      - /app/node_modules  # Prevent overwriting node_modules inside container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot-reloading in Docker
    depends_on:
      - backend  # Ensure backend starts before the frontend

  mongo:
    image: mongo:latest  # Use official MongoDB image
    volumes:
      - mongo-data:/data/db  # Persistent data storage for MongoDB
    ports:
      - "27017:27017"  # Expose MongoDB on localhost:27017

volumes:
  mongo-data:
